// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9GPXgteLqd7nZjhUR48fRYHm-ACyLuDM',
    appId: '1:143353797930:web:cd3d8a33b14a34ecea9253',
    messagingSenderId: '143353797930',
    projectId: 'go-qreate-teams',
    authDomain: 'go-qreate-teams.firebaseapp.com',
    storageBucket: 'go-qreate-teams.appspot.com',
    measurementId: 'G-HH15Q350L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWyDe5XiZBeVAdNTogM66kO2pNGnViwE',
    appId: '1:143353797930:android:c20f7abba7970b9cea9253',
    messagingSenderId: '143353797930',
    projectId: 'go-qreate-teams',
    storageBucket: 'go-qreate-teams.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwavDiw-DTejGQ8qvATgYvxwO3FMRGsnw',
    appId: '1:143353797930:ios:1dc7d6ad317f214bea9253',
    messagingSenderId: '143353797930',
    projectId: 'go-qreate-teams',
    storageBucket: 'go-qreate-teams.appspot.com',
    iosBundleId: 'com.example.goQreateTeams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwavDiw-DTejGQ8qvATgYvxwO3FMRGsnw',
    appId: '1:143353797930:ios:4141e37676abd263ea9253',
    messagingSenderId: '143353797930',
    projectId: 'go-qreate-teams',
    storageBucket: 'go-qreate-teams.appspot.com',
    iosBundleId: 'com.example.goQreateTeams.RunnerTests',
  );
}
